### ISSUE TITLE
Game stuck on loading screen and shows word 'STATUS'

### ISSUE THREAD

**Issue by fruitsbar** [Real-Gecko/KSP-WarpDrive#2]
When I try to load into the game, it gets stuck on the loading screen and has the word 'STATUS' in the middle of it. Please fix this.

**Comment by Real-Gecko** [comment]
As I mentioned [here](https://forum.kerbalspaceprogram.com/index.php?/topic/169185-leaving-community-dropping-mod-support/&) I'm not supporting this mod anymore. Mod is now maintained by one and only [FreeThinker](https://forum.kerbalspaceprogram.com/index.php?/profile/117389-freethinker/) himself. Ask him to fix the issue.
